DROP table emp;
CREATE TABLE emp (
	num NUMBER,
	name VARCHAR(20),
	hire DATE,
	PRIMARY KEY(NUM)

);

DROP SEQUENCE emp_seq;
CREATE SEQUENCE emp_seq INCREMENT BY 1 START WITH 1 NOCACHE NOCYCLE;

INSERT INTO emp VALUES(emp_seq.nextval, '이정재', SYSDATE);
COMMIT